# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchGithub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SearchGithub
# RX Pods
pod 'RxSwift',    '~> 4.0'
pod 'RxCocoa',    '~> 4.0'

# Caching Images
pod 'Kingfisher'

  target 'SearchGithubTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
